// <auto-generated />
namespace MySens.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationshipteachercourses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationshipteachercourses));
        
        string IMigrationMetadata.Id
        {
            get { return "201511261044248_relationship-teacher-courses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
